# Generated by Django 5.2.1 on 2025-06-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
